version: '3.8'

services:
  task-backend:
    build:
      context: ./task-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    container_name: task-backend
    restart: unless-stopped
    networks:
      - task-network

  task-frontend:
    build:
      context: ./task-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - task-backend
    container_name: task-frontend
    restart: unless-stopped
    networks:
      - task-network

networks:
  task-network:
    driver: bridge